### ISSUE TITLE
This uses a lot of codepoints

### ISSUE THREAD

**Issue by martinthomson** [tlswg/dtls-conn-id#11]
If you subscribe to the theory that DTLS has to mux with the realtime protocols, this takes a good slice of the remaining codepoints space.  Though TLS has between 20 and 63, DTLS 1.3 takes 32-63 and the registration of 4 more would leave just 3: 29, 30, and 31.

I submit that we might be better considering the TLS 1.3 record construction with a single codepoint.  That would get us content type encryption and arbitrary padding as a secondary benefit.  All for the modest cost of one octet.

**Comment by thomas-fossati** [comment]
If DTLS 1.3 used a demux prefix scheme like the one proposed [here](https://github.com/tlswg/dtls13-spec/issues/56), this should be no longer an issue.

**Comment by ekr** [comment]
Addressed in #13
