### ISSUE TITLE
Warren Kumari's IESG review

### ISSUE THREAD

**Issue by thomas-fossati** [tlswg/dtls-conn-id#112]
> I did find "Because each party sends the value in the "connection_id" extension it wants to receive as a CID in encrypted records, it is possible for an endpoint to use a globally constant length for such connection  identifiers. " to be confusing. I was trying to figure out what *the* globally constant length is; global implied to me that everyone would use it. Could this be reworded to something like "for an endpoint to use a constant length for all such connection identifiers." or similar?

**Comment by boaks** [comment]
> Could this be reworded to something like "for an endpoint to use a constant length for all such connection identifiers." or similar?

You're right, the "globally" seems to be used in the sense of a "programming language", so the scope is a peer and the CID emitted by this peer for other peers to be used, when the other peers sends records to the emitting peer.

Maybe we find a better term than "globally" to describe that.

**Comment by thomas-fossati** [comment]
maybe "sitewide"?
