### ISSUE TITLE
Update IANA Consideration according PR #13

### ISSUE THREAD

**Issue by boaks** [tlswg/dtls-conn-id#15]
https://github.com/tlswg/dtls-conn-id/blob/master/draft-ietf-tls-dtls-connection-id.md#iana-considerations

Still contains the content types removed in PR #13.
- alert_with_cid(25)
- handshake_with_cid(26)
- application_data_with_cid(27)
- heartbeat_with_cid(28)

I guess, it should be updated towards PR #13?
- tls12_cid(25)

**Comment by hannestschofenig** [comment]
The PR can be found here: https://github.com/tlswg/dtls-conn-id/pull/33

**Comment by boaks** [comment]
The PR will fix it.
