### ISSUE TITLE
How could the inner type byte be found?

### ISSUE THREAD

**Issue by boaks** [tlswg/dtls-conn-id#16]
```
struct {
         opaque compressed[TLSCompressed.length];
         ContentType type;
         uint8 zeros[length_of_padding];
      } DTLSWrappedCompressed;
```

As far as I understand to notation above, `opaque compressed[TLSCompressed.length]` means just some bytes without an explicit encoded length (equivalent to `opaque cid[cid_length]`). So I'm not sure, how the `TLSCompressed.length`could be determined. Could your provide me hint?
Or is there a other way, to find the position of the inner type byte?

**Comment by ekr** [comment]
All of the type bytes are non-zero, so you just work backward until you find one. This is documented in the TLS 1.3 spec, but I guess we could add text here.

**Comment by boaks** [comment]
Thanks! 
I was on the wrong path trying to determine the compressed length.
