### ISSUE TITLE
Is CompressionMethod.null supported for DTLSWrappedCompressed?

### ISSUE THREAD

**Issue by boaks** [tlswg/dtls-conn-id#17]
According https://github.com/tlswg/dtls-conn-id/blob/master/draft-ietf-tls-dtls-connection-id.md#record-payload-protection all records seems to use a `compressed : The value of DTLSCompressed.fragment`. Does this include the `CompressionMethod.null`?

**Comment by hannestschofenig** [comment]
Does this PR provide an improvement help? https://github.com/tlswg/dtls-conn-id/pull/34

**Comment by boaks** [comment]
Yes, it clarifies it for me.
