### ISSUE TITLE
Available implementations?

### ISSUE THREAD

**Issue by boaks** [tlswg/dtls-conn-id#18]
Is there a implementation available to test interoperability?

I currently plan to introduce in a open source project (californium/scandium, https://github.com/eclipse/californium) and it would make it much easier, if such a implementation is available.

**Comment by hannestschofenig** [comment]
Huawei is working an updated implementation and so do I. We can start interop testing in Jan 2019, if you want.

**Comment by boaks** [comment]
That would be great.
At least "with itself", californium's scandium works in the meantime :-) ! 

For interop testing,  the used number for the extension in the test should be clear.
And the content and format of the additional data. 

My current state of work in progress:
https://github.com/eclipse/californium/archive/wip_add_dtls_cid.zip
The demo-apps/cf-secure is prepared to used a CID (client -> server).

**Comment by thomas-fossati** [comment]
> My current state of work in progress:
> https://github.com/eclipse/californium/archive/wip_add_dtls_cid.zip
> The demo-apps/cf-secure is prepared to used a CID (client -> server).

I have cloned the californium repo and switched to the `wip_add_dtls_cid` branch.  Unfortunately, I get errors when I try to compile the project using instructions in the README.md file.

**Comment by thomas-fossati** [comment]
another WIP implementation is at https://github.com/thomas-fossati/dtls/blob/master/CID.md

**Comment by boaks** [comment]
> Unfortunately, I get errors when I try to compile the project using instructions in the README.md file.

`mvn clean install`

reports errors? Could you please provide the log with the errors? Here, or may be as comment in https://github.com/eclipse/californium/issues/824

**Comment by boaks** [comment]
> another WIP implementation is at https://github.com/thomas-fossati/dtls/blob/master/CID.md

Great, I will try that at the weekend.

**Comment by boaks** [comment]
@thomas-fossati 

I managed to try your dtls-cid implementation.
Unfortunately, the implementation seems not to share a common cipher suite with californium/scandium.

From your CLIENT_HELLO

```
Cipher Suites (4 suites)
    Cipher Suite: TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 (0xc02b)
    Cipher Suite: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 (0xc02f)
    Cipher Suite: TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA (0xc00a)
    Cipher Suite: TLS_RSA_WITH_AES_256_CBC_SHA (0x0035)
```

From my CLIENT_HELLO using X509

```
Cipher Suites (2 suites)
    Cipher Suite: TLS_ECDHE_ECDSA_WITH_AES_128_CCM_8 (0xc0ae)
    Cipher Suite: TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256 (0xc023)
```

**Comment by boaks** [comment]
@thomas-fossati 

I add `TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA (0xc00a)` to my wip and validated its compatibility with openssl (see scripts in californium demo-apps/cf-secure folder).

But with the GO implementation I could not establish successfully a connection.
As far as I could analyze, the master secret is the same, but the hash of the messages differs. Anyway, maybe you can check the compatibility with openssl using that cipher suite `TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA`?  

(I would have created an issue in the linked github repo, but I couldn't find the button for new issues there.)

**Comment by boaks** [comment]
Though GO uses the currently next "unassigned number for extensions (52)", I can switch to that.
Does mbedTLS uses also this number?

**Comment by boaks** [comment]
@thomas-fossati

I added now also TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 (0xc02b). Same result, works with openssl but GO reports:

```
expect:    5f 20 72 4c d2 be 76 c4 e2 20 5b bc
received:  9f a0 20 ab 29 e4 f0 6a a3 ac c5 56
panic: dtls: Expected and actual verify data does not match
```

I pushed the changes to my wip. I tested using GO as server (port 5684) and the cf-secure `SecureClient` with argument `X509_TRUST`.

**Comment by boaks** [comment]
The californium wip is online :-).

californium.eclipse.org:5684   for coap over dtls supporting cid after the handshake
californium.eclipse.org:5784   for coap over dtls supporting cid also during the handshake

For no coap clients, just send  four bytes 40 00 12 35 (coap ping with MID 1235). 
The answer should be  70 00 12 35 (RST for MID 1235).

**Comment by thomas-fossati** [comment]
> The californium wip is online :-).

@boaks great!
 
> californium.eclipse.org:5684 for coap over dtls supporting cid after the handshake

I've just tried my client against this endpoint.  Client sends the CID extension (I'm using 52) with a 0-length CID and gets back an handshake failure alert after CH.

**Comment by thomas-fossati** [comment]
> @thomas-fossati
> 
> I added now also TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 (0xc02b). Same result, works with openssl but GO reports:
> 
> ```
> expect:    5f 20 72 4c d2 be 76 c4 e2 20 5b bc
> received:  9f a0 20 ab 29 e4 f0 6a a3 ac c5 56
> panic: dtls: Expected and actual verify data does not match
> ```
> I pushed the changes to my wip. I tested using GO as server (port 5684) and the cf-secure `SecureClient` with argument `X509_TRUST`.

I have fixed one thing on server side and now I have no problem interop'ing with openssl (both client and server).  Could you please try again?

**Comment by boaks** [comment]
> (I'm using 52) 

I adapted to that value in the wip.

> gets back an handshake failure alert after CH.

After CLIENT_HELLO? Could your please provide the wireshark capture of your CH?

The cid in the extension is documented as 

```
struct {
      opaque cid<0..2^8-1>;
  } ConnectionId;
```

So I encoded it with "uint8 cid_length, cid-bytes". do you use also a length?

**Comment by boaks** [comment]
> I have fixed one thing on server side and now I have no problem interop'ing with openssl (both client and server). Could you please try again?

Thanks for the update! I will check it today a little later.

**Comment by thomas-fossati** [comment]
> After CLIENT_HELLO? Could your please provide the wireshark capture of your CH?
> 
> The cid in the extension is documented as
> 
> ```
> struct {
>       opaque cid<0..2^8-1>;
>   } ConnectionId;
> ```
> 
> So I encoded it with "uint8 cid_length, cid-bytes". do you use also a length?

This is the 0-length CID extension sent by the client:
```
ext type (52):
    0x00 0x34
ext len:
    0x00 0x01
value (the ConnectionId VLA itself):
    0x00
```

Is this not what you'd expect?

**Comment by thomas-fossati** [comment]
> > I have fixed one thing on server side and now I have no problem interop'ing with openssl (both client and server). Could you please try again?
> 
> Thanks for the update! I will check it today a little later.

Cool; one limitation to be aware of is that my client currently only handles certificate chains of length one :-)

**Comment by thomas-fossati** [comment]
> > The californium wip is online :-).
> 
> @boaks great!
> 
> > californium.eclipse.org:5684 for coap over dtls supporting cid after the handshake
> 
> I've just tried my client against this endpoint. Client sends the CID extension (I'm using 52) with a 0-length CID and gets back an handshake failure alert after CH.

FYI: I'm running `cf-secure` locally and I get the same behaviour as above when I run it without specifying `X509` on the command line:
```
17:57:30.925 INFO [DTLSConnector]: Aborting handshake with peer [/127.0.0.1:51841]: Client proposed unsupported cipher suites only
17:57:30.926 DEBUG [DTLSConnector]: Terminating connection with peer [/127.0.0.1:51841], reason [HANDSHAKE_FAILURE]
```
Is this maybe the case for the public endpoint?

Another interesting thing I've noticed while running `cf-secure` locally is that even though my client sends the (0-length) CID extension, server seems to ignore it (it's not mirrored in the SH).

**Comment by boaks** [comment]
Please update my wip (git pull --force).

You use cid_length and cid in the aad?

With the go server and the cf-secure client using "X509_TRUST CID:0"  I get a "Connected" and then a "Disconnected" (maybe the binary payload is not expected).

With cf-secure server "X509 NO_AUTH CID:4" and your client I get "panic: dtls: Expected and actual key signature do not match".  I will check that more detailed at the weekend.

**Comment by boaks** [comment]
> Another interesting thing I've noticed while running cf-secure locally is that even though my client sends the (0-length) CID extension, server seems to ignore it (it's not mirrored in the SH).

yes, please add "CID:4" to the argument line. And NO_AUTH to suppress the client certificate request.

**Comment by boaks** [comment]
[cid_certificates.zip](https://github.com/tlswg/dtls-conn-id/files/2793389/cid_certificates.zip)

The captures with the certificates. Where can I find your certificate? May be using that is more successful :-).

**Comment by boaks** [comment]
Some updates:

The go implementation seems to have issues as client, if the group `secp256r1` is used instead of `x25519`. You may check this with openssl using "-named_curve prime256v1" to force openssl to use the `secp256r1` instead of `x25519`. (Californium/scandium currently doesn't support `x25519`.) The reported error from go is "Expected and actual key signature do not match", with both openssl and californium/scandium as server.

Using go as server doesn't show this effect and the handshake can be finished.
Using the cid_length in aad (PR #29 would removed that) and always add a 0 pad (even if AEAD is used, which doesn't require padding) I can send data successfully to the go server. 
Go currently doesn't send the FINISHED with tls_cid and if a FINISHED with tls_cid is received, " unhandled wrapped content type: 22" is reported. I prepared a work around commit, but I must clean it up much more before I can PUSH it. I hope I can update the wip during this week (may be today).

@thomas-fossati 
If possible, can you check the go client forcing to use `secp256r1`?

**Comment by boaks** [comment]
I pushed the update and left a comment https://github.com/eclipse/californium/issues/824#issuecomment-458263651

**Comment by thomas-fossati** [comment]
hi @boaks 

> If possible, can you check the go client forcing to use secp256r1?

thanks!  this should be fixed [now](https://github.com/thomas-fossati/dtls/commit/dbde4c64ba7e68a12ce5cc7649d8a29a08261f9d)

**Comment by thomas-fossati** [comment]
quick update: Scandium and the go implementation interop OK, both client and server and over volatile 4-tuples.  Cool :-)

**Comment by boaks** [comment]
> Cool :-)

Indeed! The basic idea of this draft is really straight forward to implement. 
Some of the crypto-details, which are discussed (e.g. MAC) must sure be implemented based on the same definition, but that's not too surprising. 

FMPOV, for sustainability, the scope of the draft should be discussed. Otherwise I would be afraid, that assumption for "special use-cases" will break too much the interoperability. But lets open a new issue for that.

**Comment by boaks** [comment]
@hannestschofenig 

https://github.com/tlswg/dtls-conn-id/issues/28#issuecomment-459279854

"I believe we should allow cid usage already in the handshake itself rather than just for application layer payloads."

I will try to polish my approach over the next weekend and push it to the californium sandbox (coaps://californium.eclipse.org:5784) (5684 will be "cid not used in the handshake").

**Comment by hannestschofenig** [comment]
I tried to compile the Californium code and here are the error messages I get: 


[ERROR] /home/hannes/californium/californium-core/src/main/java/org/eclipse/californium/core/network/config/NetworkConfig.java:423: Undefined reference: void AutoCloseable.close()
[ERROR] /home/hannes/californium/californium-core/src/main/java/org/eclipse/californium/core/network/config/NetworkConfig.java:423: Undefined reference: void Throwable.addSuppressed(Throwable)
[ERROR] /home/hannes/californium/californium-core/src/main/java/org/eclipse/californium/core/network/config/NetworkConfig.java:423: Undefined reference: void AutoCloseable.close()


[ERROR] Failed to execute goal org.codehaus.mojo:animal-sniffer-maven-plugin:1.17:check (default) on project californium-core: Signature errors found. Verify them and ignore them with the proper annotation if needed. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :californium-core

**Comment by boaks** [comment]
Which java jdk do you use?
 
> java -version
> javac -version

If I  remember well, I saw a similar error last year, when I used java11 on ubuntu 18.04. 
With the current jave update it seems to be solved.

I use java8 (build 1.8.0_191-8u191-b12-2ubuntu0.18.04.1-b12) and java11 (build 11.0.1+13-Ubuntu-3ubuntu118.04ppa1).

If you use the "wip_add_dtls_cid" please note, that the last commit contains fixes for go. 
Please use the commit before that (currently df6464eb9390). 
Scandium uses currently 52 for the hello extension.

**Comment by boaks** [comment]
The "tls_cid_record-already-in-handshake" is removed :-), 
"the commit before the go fixes" should comply to the current version of this spec.

**Comment by hannestschofenig** [comment]
> java -version
openjdk version "10.0.2" 2018-07-17
OpenJDK Runtime Environment (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4)
OpenJDK 64-Bit Server VM (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4, mixed mode)

> javac -version
javac 10.0.2

Do you have a virtual machine somewhere with Californium running properly?

**Comment by boaks** [comment]
coaps://californium.eclipse.org:5684 

it runs the "etsi plugtest server". PSK credentials
identity "password" secret "sesame" (or hex 736573616D65)

Since today, the snapshot of the plugtest server is also available at

https://repo.eclipse.org/content/repositories/californium-snapshots/org/eclipse/californium/cf-plugtest-server/2.0.0-SNAPSHOT/ 

for download.

If you put `@NotForAndroid` also direct before the class definition, 
`public final class NetworkConfig {` it may also compile with java 10. 
But it's not that tested with java 10 (closer to not tested :-) ).

**Comment by boaks** [comment]
If you want to use a coap-request

GET coaps://californium.eclipse.org/large

**Comment by hannestschofenig** [comment]
I re-installed a new version of Ubuntu from scratch and the error is gone.

**Comment by boaks** [comment]
:-). That sounds good. Remember not to use the HEAD of the wip-branch, it contains the fixes for the "go" implementation (finish without cid). Please use the commit before.

**Comment by boaks** [comment]
@thomas-fossati 

In the meantime I was able to test your update.
The FINISH seems to be still a HANDSHAKE record instead of a TLS_CID record.
All other issues are solved.

**Comment by boaks** [comment]
Just for those, who are interested: 
Based on the CID and the californium implementation I prepared a demonstration load-balancer setup. 
See https://github.com/eclipse/californium/wiki/DTLS-1.2-connection-ID-based-load-balancer

**Comment by ekr** [comment]
I'm going to close this because we want to get to issues 0.
