### ISSUE TITLE
cid, CID, connection id, and connection ID

### ISSUE THREAD

**Issue by martinthomson** [tlswg/dtls-conn-id#23]
It probably makes sense to be a little more consistent.

**Comment by hannestschofenig** [comment]
Makes sense. I will do this after the current wave of pull requests have been reviewed and accepted/rejected.

**Comment by hannestschofenig** [comment]
I addressed this issue in PR #42

**Comment by hannestschofenig** [comment]
Addressed with submitted draft version -04
