### ISSUE TITLE
Parse the records without knowing how long the Connection ID is

### ISSUE THREAD

**Issue by boaks** [tlswg/dtls-conn-id#27]
https://github.com/tlswg/dtls-conn-id/blob/master/draft-ietf-tls-dtls-connection-id.md#record-layer-extensions

> Note that for both record formats, it is not possible to parse the records without knowing how long the Connection ID is.

FMPOV,  searching for the "length field" assuming that it's that uint16 pointing to the end of the UDP datagram, should result in many cases in the right length for the connection id. Moving the connection id after the "length field", will hide it from that search, but with the AEAD explicit nonce copied from the header, it will also be easy to find there.
Therefore, if it's intended to hide the connection id length in tls12_cid records, it must be after the "length field", and the explicit nonce could not longer be copied from the header to the fragment (saving 8 bytes).
It's no issue, if there is no intention to hide the connection id length. But then the misguided note above should be removed.

**Comment by ekr** [comment]
We're not hiding the CID length. It's transmitted in the clear in the handshake.

**Comment by boaks** [comment]
So what's the message of  

> Note that for both record formats, it is not possible to parse the records without knowing how long the Connection ID is.

it is in many cases possible.
