### ISSUE TITLE
Should mixed usage of cid and no-cid for one connection-endpoint be supported? 

### ISSUE THREAD

**Issue by boaks** [tlswg/dtls-conn-id#28]
If a cid is negotiated for a connection-endpoint, is it then intended to use that in all records for that connection-endpoint (at least all first records of a datagram)?

**Comment by hannestschofenig** [comment]
Yes, if you negotiate it with the other peer then you use it. Note, however, that there is still the option that the client uses a CID in the records sent to the server while the server doesn't include a CID in the records sent to the client. This is what is shown in the example. IMHO is a very common case.

**Comment by boaks** [comment]
My intention was, that, even if y cid is negotiated, and a "starting record" contains such a cid, following records may use the old record layer to save some bytes. Especially, if the cid could be extended into the not encrypted handshake messages, I would prefer to just use the cid for the first record in the datagram and save the bytes by not using the cid in the other handshake messages of the same datagram.

**Comment by hannestschofenig** [comment]
The mix of CID and non-CID payloads should be supported by the current draft since (I believe) we don't force the client or the server to always attach the CID. I double-checked the text and I didn't see anything that would prohibit you doing so. Of course, we should be explicit about features we offer. 

FWIW we allow this behavior (and more record format changes) in DTLS 1.3 thanks to the bitmask in the record header and the variable length encoding.

**Comment by boaks** [comment]
Thanks, that clarification will help to implement it proper.
Just one hint for the spec:
Using CID and non-CID, it must be clear, that potentially messages are reordered and so non-CID messages may be silently ignored. Therefore, mixing CID and non-CID is possible, but must be used with special care.

**Comment by hannestschofenig** [comment]
I am not sure why this matters here since messages may in general get re-ordered with a UDP-based transport

**Comment by boaks** [comment]
Yes, and one consequence of this reorder would be, that a message without CID send after a message with CID, are received potentially in the reverse order, what then cause **additionally** a drop. It's also true, the messages may always get dropped. I just want to make it clear by the hint, that such mix must be used with special care.

**Comment by ekr** [comment]
I believe you should be required to send CID always. That's the implied semantics of the extension and there's no basis for knowing that the receiver would like something different.

**Comment by boaks** [comment]
> there's no basis for knowing that the receiver would like something different

This draft would be the basis, because it would define, what the receiver should know :-). 

One reason would be "saving traffic". Assuming a communication pattern, that after a period of "silence", the peers will exchange a couple of messages with a frequency of some seconds. Or even many messages, if something as a "coap-blockwise-download" is considered. Such a mixed usage would enable implementations to save traffic. The first message after the silence will use the cid, but on success, the peers may switch to the old record-layer.

A second reason would be to use the cid in the handshake for the handshake messages themselves (see issue #26). It would make sense to add the cid only to the first record of a UDP message to save the traffic for the other records of the flight in the same UDP message.

Generally, if a implementation doesn't use the mix active when sending messages, the support of receiving such mixed messages is not that complex. It requires to update the ip-address, when a cid record is processed successful. Though this is anyway a "extension", the other functionality using the ip-address:port will work as usual.

**Comment by ekr** [comment]
On Sun, Jan 27, 2019 at 10:51 PM Achim Kraus <notifications@github.com>
wrote:

> there's no basis for knowing that the receiver would like something
> different
>
> This draft would be the basis, because it would define, what the receiver
> should know :-).
>

The draft has no mechanism for saying "I only want the CID some of the time"

One reason would be "saving traffic". Assuming a communication pattern,
> that after a period of "silence", the peers will exchange a couple of
> messages with a frequency of some seconds. Or even many messages, if
> something as a "coap-blockwise-download" is considered. Such a mixed usage
> would enable implementations to save traffic. The first message after the
> silence will use the cid, but on success, the peers may switch to the old
> record-layer.
>
> A second reason would be to use the cid in the handshake for the handshake
> messages themselves (see issue #26
> <https://github.com/tlswg/dtls-conn-id/issues/26>). It would make sense
> to add the cid only to the first record of a UDP message to save the
> traffic for the other records of the flight in the same UDP message.
>
> Generally, if a implementation doesn't use the mix active when sending
> messages, the support of receiving such mixed messages is not that complex.
> It requires to update the ip-address, when a cid record is processed
> successful. Though this is anyway a "extension", the other functionality
> using the ip-address:port will work as usual.
>
I'm not denying that there are potential reasons why one might want to use
a CID some of the time; I'm saying that the draft doesn't define a way to
indicate that the receiver can handle it, and given that the purpose of
this draft is to be the very minimal CID implementation, I don't think we
should add one.

**Comment by boaks** [comment]
> I'm saying that the draft doesn't define a way to indicate that the receiver can handle it

I don't get this. In my understanding, a server must support at least, that some clients are using the cid and some are not. With that, why should a peer deny to process a record without cid, that would match the connection based on the previous mechanism using address:port? 
 
If this draft has the purpose as described in introduction ("NAT rebinding"), I don't see, the "benefit" to force a peer to drop a message (without cid), which could be processed (based on the address:port).

**Comment by ekr** [comment]
On Sun, Jan 27, 2019 at 11:19 PM Achim Kraus <notifications@github.com>
wrote:

> I'm saying that the draft doesn't define a way to indicate that the
> receiver can handle it
>
> I don't get this. In my understanding, a server must support at least,
> that some clients are using the cid and some are not.
>
No. It  can simply refuse to negotiate TLS with a client which doesn't
offer the extension, for instance.



> If this draft has the purpose as described in introduction ("NAT
> rebinding"), I don't see, the "benefit" to force a peer to drop a message
> (without cid), which could be processed (based on the address:port).
>
It avoids indeterminate behavior with a given client.

**Comment by boaks** [comment]
> It avoids indeterminate behavior with a given client.

If you provide an example for that, I may have a chance to understand, why a peer, using this extension, should drop a message, which would be processed without this extension.

Sure, a specification could specify whatever.

Very general, I thought, the intention of this draft was to improve the loss caused by message dropping. But I get more and more the feeling, it is intended to provide "more", even if not mentioned explicit.

**Comment by ekr** [comment]
On Sun, Jan 27, 2019 at 11:34 PM Achim Kraus <notifications@github.com>
wrote:

> It avoids indeterminate behavior with a given client.
>
> If you provide an example for that, I may have a chance to understand, why
> a peer, using this extension, should drop a message, which would be
> processed without this extension.
>
Requiring the CID always provides deterministic behavior. Dropping the
packet when the CID is omitted enforces correct behavior.

**Comment by boaks** [comment]
> Requiring the CID always provides deterministic behavior.

Sure, therefore I wrote above https://github.com/tlswg/dtls-conn-id/issues/28#issuecomment-452058388

"Therefore, mixing CID and non-CID is possible, but must be used with special care."

In my opinion, the trade of between "works deterministic" and "uses less traffic" should be left to the implementation.  

> Dropping the packet when the CID is omitted enforces correct behavior.

There is still no reason to drop the packet, except forcing someone to "use more traffic".

So the focus here will be:
- MUST a peer drop a non-CID record, if CID is negotiated
- MUST a peer process a non-CID record, even if CID is negotiated

With the "drop", please clarify the usage of empty CID! 
 

(I edited my comment, the SHALL was wrong)

**Comment by ekr** [comment]
On Mon, Jan 28, 2019 at 12:03 AM Achim Kraus <notifications@github.com>
wrote:

> Requiring the CID always provides deterministic behavior.
>
> Sure, therefore I wrote above #28 (comment)
> <https://github.com/tlswg/dtls-conn-id/issues/28#issuecomment-452058388>
>
> "Therefore, mixing CID and non-CID is possible, but must be used with
> special care."
>
> In my opinion, the trade of between "works deterministic" and "uses less
> traffic" should be left to the implementation.
>
Well, this is something we disagree on. The next thing to do is take it to
the list.

Dropping the packet when the CID is omitted enforces correct behavior.
>
> There is still no reason to drop the packet, except forcing someone to
> "use more traffic".
>
I've already explained the reason. It enforces the correct behavior. See:
https://datatracker.ietf.org/doc/html/draft-iab-protocol-maintenance


> So the focus here will be:
>
>    - MUST a peer drop a non-CID record, if CID is negotiated
>    - SHALL a peer process a non-CID record, even if CID is negotiated
>
> With the MUST, please clarify the usage of empty CID!
>
As I said, empty CID should mean "use the 6347 framing"

**Comment by boaks** [comment]
> The next thing to do is take it to the list.

That would be great. 
Sure, if the majority votes for "force CID" (MUST drop), then the risk of "uncontrolled optimizers" will be much smaller.

**Comment by hannestschofenig** [comment]
I will create a PR to note that the padding added by this draft adds a privacy feature that wasn't there in DTLS 1.2. 

I think I clarified the use of the MAC calculation but will double-check whether I have correctly captured everything. Given the discussions we had on that issue I am sure there is more room for explanatory text. 

I believe we should allow cid usage already in the handshake itself rather than just for application layer payloads. I can see how this will become useful when DTLS is carried over non-IP-based protocols. Code-wise this does not cost much either, at least as far as I can tell. Will have to integrate it into my code to see whether that's indeed correct.

**Comment by boaks** [comment]
Thanks!

Considering https://datatracker.ietf.org/doc/html/draft-iab-protocol-maintenance I start to think about the right way for such extensions. Also in order to finish this draft. 
May be the right way to do this is:
- being "strict" with this draft 
- add the new use-case in a later draft.
-- for the extensibility either 
--- add flags to the Hello Extensions
--- or use additionally new the Hello Extensions

e.g. the "payload length obfuscation only" may be indicated by just a new additional Hello Extension. It may reuse the new record type definition of this draft and add the use of empty cids with the new record type.

**Comment by hannestschofenig** [comment]
I prefer not to have a separate extension for the payload obfuscation. If someone wants to use the cid extension then they could also use the obfuscation but I wouldn't want to introduce it as a standalone feature. DTLS 1.3 provides much better privacy features and implementations will switch to 1.3 sooner or later anyway. I see the DTLS 1.2 CID work as an intermediate solution for those deployments where DTLS 1.2 is in use and a fix is urgently needed.

**Comment by boaks** [comment]
See https://github.com/tlswg/dtls-conn-id/issues/26#issuecomment-459676265
