### ISSUE TITLE
future extensions of cid / position of the cid

### ISSUE THREAD

**Issue by boaks** [tlswg/dtls-conn-id#36]
According the comment https://github.com/tlswg/dtls-conn-id/issues/25#issuecomment-444890710 I would assume, that this draft will be involved in future extensions.

If that assumption "future extensions" is true, the definition of `ExtensionType` should be extended from a "simple plain cid" to a "list of typed cids", where currently only the "plain" type is defined and used. That would allow future extensions for other cid types (e.g. types, which are less traceable).

If such future extensions should be supported, I have doubts about the current position of the cid, see my issue #27 . I would prefer to move the cid behind the length to protect it from being "discovered" too easy.

(I'm also OK, if this draft should be "finalized" and future extensions are not long considered for DTLS 1.2 . )

**Comment by hannestschofenig** [comment]
I doubt that the DTLS 1.2 CID will be enhanced in future extensions since we already have DTLS 1.3, which provides better performance, security and privacy properties.

If the CID is in the header than an eavesdropper will see it. The only mitigation appears to be to change the CID on specific events, which DTLS 1.3 supports.

**Comment by boaks** [comment]
> If the CID is in the header than an eavesdropper will see it.

Yes, and I don't plan to extend this. But from the past there have been discussion about that. And a "list of types" would make it possible for others to extend this in the future.
But, as I already wrote, I'm OK with not planning too much future extensions for DTLS 1.2 CID.
