### ISSUE TITLE
cid=empty=?padding?

### ISSUE THREAD

**Issue by martinthomson** [tlswg/dtls-conn-id#43]
>A zero-length value indicates that the client is prepared to send with a connection ID but does not wish the server to use one when sending (alternately, this can be interpreted as the client wishes the server to use a zero-length CID; the result is the same).

This implies that an empty CID and an absent CID are identical.  But they don't have to be. If both endpoints negotiate a zero- length CID, then this extension could be used to enable record padding.

The doc is not clear on this point. If a peer sends an empty connection_id extension, what are you supposed to do:

1. MUST send records in the old format.
2. MUST send tls12_cid records (which could be padded).
3. MAY send either.

It seems like option 2 or 3 give us a nice new feature - the ability to pad records - though 2 forces an additional overhead of 1 byte. Option 3 is somewhat less deterministic though (it doesn't seem like it would be harder to implement though).

**Comment by ekr** [comment]
On Fri, Feb 1, 2019 at 9:38 PM Martin Thomson <notifications@github.com>
wrote:

> A zero-length value indicates that the client is prepared to send with a
> connection ID but does not wish the server to use one when sending
> (alternately, this can be interpreted as the client wishes the server to
> use a zero-length CID; the result is the same).
>
> This implies that an empty CID and an absent CID are identical. But they
> don't have to be. If both endpoints negotiate a zero- length CID, then this
> extension could be used to enable record padding.
>
> The doc is not clear on this point. If a peer sends an empty connection_id
> extension, what are you supposed to do:
>
>    1. MUST send records in the old format.
>    2. MUST send tls12_cid records (which could be padded).
>    3. MAY send either.
>
> It seems like option 2 or 3 give us a nice new feature - the ability to
> pad records - though 2 forces an additional overhead of 1 byte. Option 3 is
> somewhat less deterministic though (it doesn't seem like it would be harder
> to implement though).
>
I agree that the old text is wrong. It comes from a previous encoding and
MAC structure. I don't care about the padding feature for (2) or (3), as
this is a point fix for DTLS 1.2. I could live with (2) but the
nondeterminism in (3) seems bad.

**Comment by hannestschofenig** [comment]
Addressed in submitted version -04
