### ISSUE TITLE
CID and non-AEAD ciphersuites

### ISSUE THREAD

**Issue by thomas-fossati** [tlswg/dtls-conn-id#46]
We currently only describe CID processing with AEAD ciphersuites, which seems to imply that the CID extension effectively influences ciphersuite negotiation.

The draft should explain how the two - ciphersuite negotiation and CID ext - interact.

**Comment by boaks** [comment]
I'm not sure, what the scope of this explanation should be?
For the MAC, it seems to be obvious, that the block cipher (https://tools.ietf.org/html/rfc5246#section-6.2.3.2 ) extend the data for the MAC accordingly.

https://tools.ietf.org/html/rfc5246#section-6.2.3.1

```
MAC(MAC_write_key, seq_num +
TLSCompressed.type +
TLSCompressed.version +
TLSCompressed.length +
TLSCompressed.fragment);
```

will get 

```
MAC(MAC_write_key, seq_num +
TLSCompressed.type +
TLSCompressed.version +
TLSCompressed.cid + 
cid_length +
TLSCompressed.length +
TLSCompressed.fragment);
```

That was already discussed in https://github.com/tlswg/dtls-conn-id/pull/29#issuecomment-459277192

> Then, Thomas can make a contribution for the MAC calculation for non-AEAD ciphers.

So, I'm not sure, if you are the intended "Thomas", which may write that :-)

**Comment by hannestschofenig** [comment]
The question is whether we should define the CID-enhanced MAC calculation for non-AEAD ciphers. The current draft only supports AEAD ciphers. If that's OK then we could just tell implementers that the ciphersuite selection should be influenced by this. Alternatively, we could define the MAC calculation also for non-AEAD ciphers. 

What would you prefer, Achim?

**Comment by ekr** [comment]
On Wed, Mar 6, 2019 at 8:26 AM Hannes Tschofenig <notifications@github.com>
wrote:

> The question is whether we should define the CID-enhanced MAC calculation
> for non-AEAD ciphers. The current draft only supports AEAD ciphers. If
> that's OK then we could just tell implementers that the ciphersuite
> selection should be influenced by this. Alternatively, we could define the
> MAC calculation also for non-AEAD ciphers.
>

The latter, I think...

-Ekr

What would you prefer, Achim?

**Comment by boaks** [comment]
Though Leshan (LWM2M, also supporting CBC) is one of the major using and contributing projects, I would also prefer to have the MAC defined for the none-AEAD.

**Comment by hannestschofenig** [comment]
Here is the PR: https://github.com/tlswg/dtls-conn-id/pull/47
