### ISSUE TITLE
IANA Considerations Update

### ISSUE THREAD

**Issue by seanturner** [tlswg/dtls-conn-id#66]
A couple of tweaks are needed for the IANA Considerations Section:

- Based on input from the IANA TLS DEs, it seems like we need a column added to the TLS ExtensionType Values registry to indicate that an extension is DTLS-only.
- The column values for TLS 1.3 and Recommended are missing.  Suggest blank for TLS 1.3 and N for Recommended.
- Add a note to say that connection_id is DTLS1.2 only.
- Add instructions for IANA to assign "Y" to DTLS-okay column for tls12_cid content type.

**Comment by boaks** [comment]
That results in

"DTLS only" for TLS extensions and
"DTLS-OK" for TLS parameters.

I'm not sure, if that just represents more the "current" usage than the "logic" behind it.
I would be afraid, that this will hold up other ideas, which doesn't match that "only for extensions / ok for parameters" pattern.

**Comment by hannestschofenig** [comment]
I am not sure what "DTLS-OK" for TLS parameters means

**Comment by boaks** [comment]
["DTLS-OK" for TLS parameters](https://www.iana.org/assignments/tls-parameters/tls-parameters.xhtml#tls-parameters-5)  

For TLS parameters there's a column "DTLS-OK", 
And for TLS extensions a column "DTLS only".

Does this explain my comment?

**Comment by hannestschofenig** [comment]
We added text to the draft-ietf-tls-dtls-connection-id-06 about the IANA consideration section. I believe this issue is closed.
