### ISSUE TITLE
Preconditions for accepting address update events

### ISSUE THREAD

**Issue by boaks** [tlswg/dtls-conn-id#69]
[Security and Privacy Considerations](https://github.com/tlswg/dtls-conn-id/blob/master/draft-ietf-tls-dtls-connection-id.md#security-and-privacy-considerations-sec-cons)

The part 

> When a record with CID is received that has the source address of the enclosing
> UDP datagram different from the one previously associated with that CID, the
> receiver MUST NOT update its view of the peer’s address with the source
> specified in the UDP packet before cryptographically validating the enclosed
> record(s).  This is to ensure that a man-on-the-side attacker that sends a
> packet with a different source address on an existing CID session does not
> successfully manage to reroute any return traffic.

of PR #65 didn't made to the draft, or did I miss it?

In the meantime, I would even go further:
Applying [MAC](https://tools.ietf.org/html/rfc6347#section-4.1.2.1) and [Anti-Replay](https://tools.ietf.org/html/rfc6347#section-4.1.2.6) may validates the record cryptographically, and so the receive windows may be updated and the application data may be forwarded. But, if the epoch/sequence_number is not  newer than the newest successfully validate epoch/sequence_number before, the address update event itself may be wrong! Assuming, that a address-change is located somewhere on the message's route, it seems to be not possible to distinguish, if the message was delayed after the "address change" (and so that address is deprecated) or before that (and so the address would be the new one). If that could not be decided, I would go for updating the address only for newer records.
Using that approach, updating the address only for newer records (based on epoch/sequence_number) with validated [MAC](https://tools.ietf.org/html/rfc6347#section-4.1.2.1), would also mitigate the first two attacks of issue #64, though retransmitting an record with changed address will not update the address, because these records are **NOT** newer.

**Comment by hannestschofenig** [comment]
I have updated the text of https://github.com/tlswg/dtls-conn-id/pull/70 and was wondering whether it captures your issue. I am not sure what steps I have to take to meet your requirements.

**Comment by boaks** [comment]
As long as [RFC6347, 4.1.2.6 - anti replay](https://tools.ietf.org/html/rfc6347#section-4.1.2.6) doesn't get mandatory (MUST), everything for me will be OK.

So, yes, PR #70 addresses it in the right way.

**Comment by thomas-fossati** [comment]
It looks like #70 closes this issue?

**Comment by boaks** [comment]
Thanks!
