### ISSUE TITLE
Section 8 comment from Ben's review

### ISSUE THREAD

**Issue by jsalowey** [tlswg/dtls-conn-id#79]
Section 8
 
> With multi-homing, a passive attacker is able to correlate the
>  communication interaction over the two paths and the sequence number
> makes it possible to correlate packets across CID changes.  The lack

 DTLS 1.2 CIDs don't have CID changes (other than by rehandshaking, which
resets the sequence number space); the last clause seems stale from DTLS
1.3?

**Comment by boaks** [comment]
You're right, if the CID changes, the sequence numbers are reset. So it doesn't make sense.
Maybe, "across address changes", was meant.

**Comment by kaduk** [comment]
If "across address changes" was meant then it seems like the CID itself would be an even better way to correlate packets across address changes.  It looks like this was fixed in the meantime by 094584b0d1882e4f8e570627f0aff5a9507f85e9 so we should close the issue.
