### ISSUE TITLE
Section 9 comment from Ben

### ISSUE THREAD

**Issue by jsalowey** [tlswg/dtls-conn-id#80]
>     An on-path adversary can create reflection attacks against third
>     parties because a DTLS peer has no means to distinguish a genuine
>     address update event (for example, due to a NAT rebinding) from one
>     that is malicious.  This attack is of concern when there is a large

This is why we have the "[t]here is a strategy for ensuring that the new
peer address is able to receive and process DTLS records" requirement,
right?  We should probably mention that (and that it's not perfect,
since you have to send some records to the not-yet-verified peer address
as part of the verification process).

**Comment by boaks** [comment]
> (and that it's not perfect, since you have to send some records to the not-yet-verified peer address
as part of the verification process)

To label it "perfect" or not, requires a discussion about the threats before. There are some comments/contributions, but for me this discussion seems to be still pending. 

Let me try to list them up:
- Thomas started the topic with issue #64
- Hannes proposed [draft-tschofenig-tls-dtls-rrc-00 - DTLS Return Routability Check (RRC)](https://mailarchive.ietf.org/arch/msg/tls/oTZ_t_PJ4uJ1U5cmV5oUabYvL-8/), Martin start to point to the work in QUIC.
- you started a discussion asking the mail list [WGLC for draft-ietf-tls-dtls-connection-id-06](https://mailarchive.ietf.org/arch/msg/tls/3W4t4Vs0gA-I2O_b8uBXmkjcQMc/)
- Sean started a discussion asking the mail list [WG adoption call for draft-tschofenig-tls-dtls-rrc](https://mailarchive.ietf.org/arch/msg/tls/IJYqpTmSHsCkiMaUPt_AltvKbe8/).
    - Martin requested in that discussion "To give an idea, address validation in QUIC is much more complex than is proposed here, for reasons I believe to be good.  If this document does less than QUIC, it needs to justify that."
   - and I tried to answered that. (Though QUIC "give me a word, and I download you the WEB", is something totally different to CoAP/DTLS "occasionally send a couple of bytes and get even less bytes with the processing state back ." it doesn't require the same means to defend.)

My conclusion is therefore still:
Until now, I see only an amplification attack.
To mitigate that, it's "perfect", if you send just less bytes back.

For the most other "advanced scenarios", you may use RRC, or use an mechanism on the next layers of the stack (e.g. [draft-ietf-core-echo-request-tag](https://datatracker.ietf.org/doc/draft-ietf-core-echo-request-tag/ for CoAP.)

**Comment by boaks** [comment]
@thomas-fossati 

In the [discussion Sean started](https://mailarchive.ietf.org/arch/msg/tls/IJYqpTmSHsCkiMaUPt_AltvKbe8/) you replied "I'm also happy to invest cycles to bring it to fruition."

Any further results/details?

**Comment by thomas-fossati** [comment]
> @thomas-fossati
> 
> In the [discussion Sean started](https://mailarchive.ietf.org/arch/msg/tls/IJYqpTmSHsCkiMaUPt_AltvKbe8/) you replied "I'm also happy to invest cycles to bring it to fruition."
> 
> Any further results/details?

It looks like the CfA has not concluded yet.  We should ask the chairs.

**Comment by jsalowey** [comment]
I think we need to redo the call as it was not clear if we had consensus to adopt.

**Comment by boaks** [comment]
One idea of that discussion was, to move that "open questions" to an other RFC (therefore RRC), in order to finalize this CID RFC for the use-cases, which don't require such a RRC.

The point from Martin 

> I'm really concerned about shipping a protocol that enables the sorts of attacks that connection IDs enable.  

is sure valid, but it will take a large amount of time, to verify, if QUIC does something, which is also required here. Though Tomas wait's for the "CfA" to conclude, I guess, it's still takes more time.

So for me the main question seems to be, if Martin's statement, blocks this RFC, or, not.

**Comment by thomas-fossati** [comment]
Hi Achim,

> The point from Martin
> 
> > I'm really concerned about shipping a protocol that enables the sorts of attacks that connection IDs enable.
>
> is sure valid, but it will take a large amount of time, to verify, if QUIC does something, which is also required here. Though Tomas wait's for the "CfA" to conclude, I guess, it's still takes more time.
> 
> So for me the main question seems to be, if Martin's statement, blocks this RFC, or, not.

Martin's comment ([ptr](https://mailarchive.ietf.org/arch/msg/tls/489dqAquQdQrw8cbLBIxoc8Y03Y/)) was about -06, whereas -latest has added [Section 6](https://tools.ietf.org/rfcdiff?url2=draft-ietf-tls-dtls-connection-id-09.txt&url1=draft-ietf-tls-dtls-connection-id-06.txt) to address that.

From that point of view the document should be OK in its current shape.

**Comment by boaks** [comment]
Hi Thomas,

Thanks for your clarification!

**Comment by kaduk** [comment]
So is the conclusion that Section 6 addresses this issue, and we should mark the issue as resolved?

**Comment by ekr** [comment]
I believe so, yes.

**Comment by kaduk** [comment]
Based on my review of the issue history, and looking back at my original comment (which was just "we should probably mention this [and maybe some caveats]"), I agree.  We clearly link to the entire Section 6 that goes into some not insignificant detail on the caveats, so it looks like we did what I was asking for.
