### ISSUE TITLE
Zero-length CID clarifications

### ISSUE THREAD

**Issue by thomas-fossati** [tlswg/dtls-conn-id#89]
Tom Petch's review: https://mailarchive.ietf.org/arch/msg/tls/Opmv1JCmY10uBKP1SrzfUpxhzCY/

```
s.3
I found this unclear until I had understood it all (or perhaps I do not
understand it)

"...or again, alternately, to use a zero-length CID)."
This suggests that a zero length CID is valid in Application Data which
later text seems to contradict; otherwise I cannot see what this is saying.

"  If DTLS peers have negotiated the use of a CIDs using the ClientHello
and the ServerHello messages "
arguably sending a zero CID and receiving a zero CID is a successful
Hello negotiation perhaps
" If DTLS peers have negotiated the use of a non-zero CID in at least
one direction, using the ClientHello and the ServerHello messages"

"The DTLS peers determine whether incoming and outgoing messages need.."
seems not to cater for unidirectional CIDs; perhaps
"The DTLS peers determine whether incoming or outgoing, or both,
messages need.. "
```

**Comment by boaks** [comment]
> A zero-length value indicates that the server will send with the client's CID but does not wish the client to include a CID (or again, alternately, to use a zero-length CID).

My feeling: remove "(or again, alternately, to use a zero-length CID)" and add:

The text following that seems to introduce first the idea of a "zero-length CID", and later use that to negate the use of tls_cid record. It may be more straight forward, if the "zero-length CID" is scoped to the  ClientHello and the ServerHello extensions, and later the use of a tls_cid record is then only caused for a non-empty CID.
