### ISSUE TITLE
Notation in diagram is confusing

### ISSUE THREAD

**Issue by martinthomson** [tlswg/dtls-conn-id#9]
In Figure 2, parentheses are used to signify both extensions (connection_id=100) and the addition to the record header (cid=100).  I suggest using a different notation here.

**Comment by ekr** [comment]
@hannestschofenig can you take a crack at fixing this

**Comment by hannestschofenig** [comment]
Here is an update: https://github.com/tlswg/dtls-conn-id/pull/30

**Comment by hannestschofenig** [comment]
Updated diagram merged into the draft.
