### ISSUE TITLE
new "connection_id" extension codepoint after MAC semantics change?

### ISSUE THREAD

**Issue by kaduk** [tlswg/dtls-conn-id#99]
We currently have an early allocation of the TLS extensiontype codepoint 53 that was allocated on 2019-07-02.
An implementation of the draft at that time will no longer interoperate with the current specification due to changes in how the MAC inputs and AAD are laid out.

If we want to allocate a new extensiontype value for the new semantics, we should tell IANA that there is an existing early allocation and, e.g., that it should be left to expire (and what version of the draft to use as a reference until it does), with a new codepoint to be allocated in its stead.

We also have the option to direct IANA that "once this document is approved for publication, the early allocation will be deprecated and the following assignment will be made".

**Comment by ekr** [comment]
I think we should take your last option.
